name: Deploy and Destroy EKS Clusters

on:
  push:
    branches:
      - 'Cluster-1'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: modules/eks

    steps:
      - name: Checkout cluster branch
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy EKS Cluster 
        run: |
          terraform init
          terraform plan   
          terraform apply 

      - name: Destroy EKS Cluster 
        if: always()
        run: |
          terraform init
          terraform destroy -auto-approve 








