name: Deploy and Destroy EKS Cluster

on:
  push:
    branches:
      - 'Cluster-1'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: modules/eks

    steps:
      - name: Checkout cluster branch
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Deploy EKS Cluster
        run: |
          terraform init 
          terraform plan -var "vpc_id=${{ vars.VPC_ID }}" -var "cluster_name=${{ vars.CLUSTER_NAME_CLUSTER_1 }}" -var "cluster_version=${{ vars.CLUSTER_VERSION_CLUSTER_1 }}" -lock=false
          terraform apply -var "vpc_id=${{ vars.VPC_ID }}" -var "cluster_name=${{ vars.CLUSTER_NAME_CLUSTER_1 }}" -var "cluster_version=${{ vars.CLUSTER_VERSION_CLUSTER_1 }}" -auto-approve

      - name: Create Namespace
        run: |
          terraform init
          terraform plan -target=kubernetes_namespace.nginx -out=namespace_plan.out
          terraform apply namespace_plan.out

      - name: Deploy NGINX Ingress Controller
        run: |
          terraform plan -target=helm_release.nginx_ingress -out=nginx_ingress_plan.out
          terraform apply nginx_ingress_plan.out