name: Generate kubeconfig

on:
  push:
    branches:
      - 'Cluster-1'
  workflow_dispatch:

jobs:
  generate_kubeconfig:
    runs-on: ubuntu-latest
    steps:
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name Cluster-1
          KUBECONFIG_CONTENT=$(cat ~/.kube/config)
          echo "::set-output name=kubeconfig_content::$KUBECONFIG_CONTENT"

      - name: Store kubeconfig content as secret
        run: |
          echo "${{ steps.generate_kubeconfig.outputs.kubeconfig_content }}"  # Debugging step
          echo "${{ steps.generate_kubeconfig.outputs.kubeconfig_content }}" > kubeconfig
        shell: bash

      - name: Save kubeconfig as artifact
        uses: actions/upload-artifact@v2
        with:
          name: kubeconfig
          path: kubeconfig
